### ISSUE TITLE
broken

### ISSUE THREAD

**Issue by ImNotHumanAnymore** [amethystnetwork-dev/Incognito#16]
its broken 
![Uploading Screen Shot 2022-11-16 at 13.52.02.png…]()

**Comment by AsherSaenz** [comment]
How so I can not see the screenshot you have sent.

**Comment by ImNotHumanAnymore** [comment]
<img width="1440" alt="Screen Shot 2022-11-16 at 13 52 02" src="https://user-images.githubusercontent.com/118389605/202452713-e2002420-334d-4470-aaa3-c05db5ee0a32.png">

**Comment by ImNotHumanAnymore** [comment]
ive updated my browser and i restarted my computer

**Comment by mdoryammilwalrus** [comment]
When that message appears it means that service workers are not compatible. I had updated the loading page error message to say what the error is, you should update your deployment.

**Comment by ImNotHumanAnymore** [comment]
ok
